version: 2.1

aliases:
  - &working_directory ~/gonevis-dash-2

executors:
  node:
    docker:
      - image: circleci/node:latest-browsers
    working_directory:  *working_directory

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: |
            npm install
            ./node_modules/.bin/ngcc --properties es2015 browser module main --async false
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: *working_directory
          paths:
            - .

  e2e:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - run:
          name: End 2 End
          command: npm run e2e
  lint:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - run:
          name: code quality
          command: npm run lint
  test:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - run:
          name: test
          command: npm run test
      - run:
          name: code-coverage
          command: 'npm run report-coverage'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml

  deploy:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - run:
          name: Deploying to Production
          command: |
            sudo apt -y install rsync
            chmod u+x scripts/deploy.sh
            ./scripts/deploy.sh
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - e2e:
          requires:
            - build
      - deploy:
          requires:
            - build
            - e2e
            - lint
          filters:
            branches:
              only:
                - master
                - production
