export const SearchSuggestions: {
  label: string
  path: string,
  keywords: string[],
}[] = [
  {
    label: 'Dashboard',
    path: 'main',
    keywords: ['main', 'overview', 'storage'],
  },
  {
    label: 'Write',
    path: 'write',
    keywords: ['editor', 'new', 'start'],
  },
  {
    label: 'Create Page',
    path: 'write/page',
    keywords: ['create', 'new', 'page', 'editor'],
  },
  {
    label: 'Settings',
    path: 'settings',
    keywords: ['settings', 'config', 'domains'],
  },
  {
    label: 'Settings > Appearance',
    path: 'settings/appearance',
    keywords: [
      'settings',
      'appearance',
      'theme',
      'color',
      'design',
      'config',
      'template',
      'logo',
      'cover image',
      'font',
    ],
  },
  {
    label: 'Settings > Advanced',
    path: 'settings/advanced',
    keywords: [
      'settings',
      'advanced',
      'google analytics',
      'google adsense',
      'webmaster tools',
      'branding',
      'custom footer',
      'meta description',
      'number of posts per page',
      'allow visitors to comment on my posts',
      'allow visitors to vote on my posts',
      'show how many times my posts have been visited',
      'let search engine discover my blog',
      'remove GoNevis.com branding',
    ],
  },
  {
    label: 'Settings > Upgrade',
    path: 'settings/upgrade',
    keywords: [
      'settings',
      'upgrade',
      'plans',
      'features',
      'unlock',
      'purchase',
      'professional',
      'personal',
      'lite',
    ],
  },
  {
    label: 'Settings > Billing',
    path: 'settings/billing',
    keywords: ['settings', 'billing', 'invoices', 'cancel', 'transactions', 'downgrade'],
  },
  {
    label: 'Tags',
    path: 'tags',
    keywords: ['tags', 'labels'],
  },
  {
    label: 'Team',
    path: 'team',
    keywords: ['team', 'members', 'authors'],
  },
  {
    label: 'Help',
    path: 'help',
    keywords: ['help', 'start', 'changes', 'feedback'],
  },
  {
    label: 'Posts',
    path: 'posts',
    keywords: ['posts', 'entry', 'entries', 'articles'],
  },
  {
    label: 'Pages',
    path: 'pages',
    keywords: ['entry', 'entries'],
  },
  {
    label: 'Comments',
    path: 'comments',
    keywords: ['reply', 'comments', 'responses', 'approve', 'pending'],
  },
  {
    label: 'Media',
    path: 'media',
    keywords: ['media', 'files', 'video', 'photo', 'storage', 'upload', 'download', 'documents', 'images'],
  },
  {
    label: 'Statistics',
    path: 'statistics',
    keywords: ['statistics', 'stats', 'views', 'data', 'overview', 'page', 'views', 'likes', 'comments', 'chart'],
  },
];
